spring:
  profiles:
    active: default

  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池
      pool-name: DataHikariCP
      # 最小连接数
      minimum-idle: 5
      # 空闲连接存活最大时间：默认600000（10分钟）
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池中返回的连接自动提交
      auto-commit: true
      # 连接池最大存活时间 ： 默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句：
      connection-test-query: SELECT 1
  redis:
    host: 39.108.99.67
    port: 6739
    connect-timeout: 10000ms
    database: 1
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
        max-active: 8
    password: 123456root
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        compressed: true
        enabled: true

      add-mappings: true
      static-locations: classpath:/static/
mybatis-plus:
  # Mapper.xml位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis-plus数据返回类型的别名
  type-aliases-package: com.xixiy.seckill.pojo
logging:
  level:
    com.xixiy.seckill.mapper: debug
